### PR TITLE
Added docs with IP examples to enum cases

### LINKED ISSUE #9: Document IP version cases
https://github.com/Samasaur1/SwiftIP/blob/08e9994dc1fdce46fe5ea60492737142c2b976cf/Sources/SwiftIP/SwiftIP.swift#L6-L9

Jazzy says that the two cases in the `Version` enum are undocumented. It's very simple to add docs to these cases (just add `/// docs` on the line above each case).

These docs should probably have examples of the formats (e.g., `192.168.10.32`)

### PR DESCRIPTION
**Pull request by IgorChernyshov**
Resolves issue #9 
I tried to keep it simple.

P.S. If you find this PR helpful, please add a label hacktoberfest-accepted to it.
Thanks

### CODE REVIEW

**Review by Samasaur1 — CHANGES_REQUESTED** [review]
Thanks for contributing! This looks good, so there's just one thing you need to do. Please modify the `.jazzy.yaml` file and change the `module_version` to `2.2.0` (this is just something you have to do because I'm still working out some problems with the setup of my repository).

**Comment by IgorChernyshov** [comment]
Sure, will do

**Review by Samasaur1 — APPROVED** [review]
Looks good to me. Thanks!

**Comment by Samasaur1** [comment]
@IgorChernyshov Just FYI, my convention for PR titles/commit messages is to use the imperative/command form of verbs, so "add ..." instead of "added ..." It's on me for not noticing that — there's no way you would have known — and you have nothing to worry about, but I'm pretty sure it's the convention.

**Comment by IgorChernyshov** [comment]
OK, thanks for letting me know!

Igor Chernyshov Sent from iPhone

Thursday, 8 October 2020, 23:58 +0300 from notifications@github.com  <notifications@github.com>:

**Pull request merged**
